config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    
]

helloworld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('website.urls', 'website'), namespace='website')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path
from .views import IndexView
from .views import FuncionarioCreateView, ListaFuncionarios, FuncionarioUpdateView
from .views import ListaFuncionarios
from .views import FuncionarioDeleteView

app_name = 'website'

urlpatterns = [
    path('funcionarios/', ListaFuncionarios.as_view(), name='lista_funcionarios'),
    path('funcionario/cadastrar/', FuncionarioCreateView.as_view(), name='cadastra_funcionario'),
    path('funcionarios/editar/<int:pk>/', FuncionarioUpdateView.as_view(), name='atualiza_funcionario'),
    path('funcionario/excluir/<int:pk>/', FuncionarioDeleteView.as_view(), name='deleta_funcionario'),
    path("", IndexView.as_view(), name="index"),

]

helloworld/models.py
from django.db import models
class Funcionario(models.Model):
    nome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )
    sobrenome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )
    cpf = models.CharField(
        max_length=14,
        null=False,
        blank=False
    )
    tempo_de_servico = models.IntegerField(
        default=0,
        null=False,
        blank=False
    )
    remuneracao = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=False,
        blank=False
    )
    objetos = models.Manager()

website/forms.py
from django import forms
from helloworld.models import Funcionario

class InsereFuncionarioForm(forms.ModelForm):
    chefe = forms.BooleanField(
        label='Este Funcionário exerce função de Chefia?',
        required=True,
    )
    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    class Meta:
        model = Funcionario

        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'remuneracao'
        ]

        exclude = [
            'tempo_de_servico'
        ]

website/views.py
from django.views.generic import CreateView, ListView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.forms import ModelForm
from helloworld.models import Funcionario
from .forms import InsereFuncionarioForm

class InsereFuncionarioForm(ModelForm):
    class Meta:
        model = Funcionario
        fields = "__all__"

class IndexView(TemplateView):
    template_name = "website/index.html"

class FuncionarioCreateView(CreateView):
    template_name = "website/cria.html"
    model = Funcionario
    form_class = InsereFuncionarioForm
    success_url = reverse_lazy("website:lista_funcionarios")

class FuncionarioDeleteView(DeleteView):
    model = Funcionario
    template_name = "website/exclui-funcionario.html"
    context_object_name = 'funcionario'
    success_url = reverse_lazy('website:lista_funcionarios')

class FuncionarioUpdateView(UpdateView):
    model = Funcionario
    fields = '__all__'
    template_name = 'website/atualiza.html'
    context_object_name = 'funcionario'
    success_url = reverse_lazy('website:lista_funcionarios')

class ListaFuncionarios(ListView):
    model = Funcionario
    template_name = 'website/lista.html'
    context_object_name = 'funcionarios'


templates/website/forms.html
<!DOCTYPE html>
<html>
<head>
    <title>Criar Funcionário</title>
</head>
<body>

<h1>Cadastrar Funcionário</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Salvar</button>
</form>

</body>
</html>

website/templates/website/_layouts/base.html
<!DOCTYPE html>
<html>
{% load static %}
{% load tempo_atual %}

<head>
    <title>
        {% block title %}Gerenciador de Funcionários{% endblock %}
    </title>

    <!-- Estilos -->
    <link rel="shortcut icon" type="image/png" href="{% static 'website/img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    
    {% block styles %}{% endblock %}
</head>
<body>

<ul class="navbar-nav float-right">
    <li class="nav-item">
        <a class="nav-link" href="#">
            <b>Hora: </b>{% tempo_atual %}
        </a>
    </li>
</ul>

<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'website:index' %}">
        <img src="{% static 'website/img/logo.png' %}" height="45px">
    </a>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:index' %}">
                    Página Inicial
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:lista_funcionarios' %}">
                    Funcionários
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block conteudo %}{% endblock %}

<script src="{% static 'website/js/jquery.min.js' %}"></script>
<script src="{% static 'website/js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
<script src="{% static 'website/js/scripts.js' %}"></script>

</body>
</html>

website/templates/website/atualiza.html
<!DOCTYPE html>
<html>
<head>
    <title>Atualizar Funcionário</title>
</head>
<body>

<h1>Atualizar Funcionário</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar alterações</button>
</form>

<a href="{% url 'website:lista_funcionarios' %}">Voltar</a>

</body>
</html>

website/templates/website/cadastro_funcionario.html
{% extends "website/_layouts/base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block title %}Cadastrar Funcionário{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'website/css/style.css' %}">
{% endblock %}

{% block conteudo %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Cadastro de Funcionário</h5>
                    <p class="card-text">
                        Complete o formulário abaixo para cadastrar
                        um novo <code>Funcionário</code>.
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        <!-- Nome -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome</span>
                            </div>
                            {% render_field form.nome class+="form-control" %}
                        </div>
                        <!-- Sobrenome -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Sobrenome</span>
                            </div>
                            {% render_field form.sobrenome class+="form-control" %}
                        </div>
                        <!-- CPF -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CPF</span>
                            </div>
                            {% render_field form.cpf class+="form-control" %}
                        </div>
                        <!-- Tempo de Serviço -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    Tempo de Serviço
                                </span>
                            </div>
                            {% render_field form.tempo_de_servico class+="form-control" %}
                        </div>
                        <!-- Remuneração -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Remuneração</span>
                            </div>
                            {% render_field form.remuneracao class+="form-control" %}
                        </div>
                        <button class="btn btn-primary">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/cria.html
{% extends "website/_layouts/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Cadastrar Funcionário{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'website/css/style.css' %}">
{% endblock %}

{% block conteudo %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Cadastro de Funcionário</h5>
                    <p class="card-text">
                        Complete o formulário abaixo para cadastrar
                        um novo <code>Funcionário</code>.
                    </p>

                    <form method="post">
                        {% csrf_token %}

                        <div class="input-group mb-3">
                            <span class="input-group-text">Nome</span>
                            {% render_field form.nome class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text">Sobrenome</span>
                            {% render_field form.sobrenome class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text">CPF</span>
                            {% render_field form.cpf class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text">Tempo de Serviço</span>
                            {% render_field form.tempo_de_servico class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text">Remuneração</span>
                            {% render_field form.remuneracao class+="form-control" %}
                        </div>

                        <button class="btn btn-primary">Salvar</button>
                        <a href="{% url 'website:lista_funcionarios' %}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/exclui-funcionario.html
{% extends "website/_layouts/base.html" %}

{% block title %}Excluir Funcionário{% endblock %}

{% block conteudo %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Exclusão de Funcionário</h5>

            <p class="card-text">
                Você tem certeza que quer excluir o funcionário
                <b>{{ object.nome }}</b>?
            </p>

            <form method="post">
                {% csrf_token %}
                <hr>
                <div class="text-right">
                    <a href="{% url 'website:lista_funcionarios' %}"
                       class="btn btn-outline-secondary">
                        Cancelar
                    </a>
                    <button class="btn btn-danger">
                        Excluir
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}


website/templates/website/funcionarios.html
{% extends "website/base.html" %}

{% block title %}Lista de Funcionários{% endblock %}

{% block conteudo %}
<h1>Lista de Funcionários</h1>

<a href="{% url 'website:cria_funcionario' %}">Cadastrar novo</a>

<hr>

{% if funcionarios %}
<table border="1">
    <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Ações</th>
    </tr>
    {% for funcionario in funcionarios %}
    <tr>
        <td>{{ funcionario.nome }}</td>
        <td>{{ funcionario.sobrenome }}</td>
        <td>
            <a href="{% url 'website:atualiza_funcionario' funcionario.id %}">Editar</a>
            |
            <a href="{% url 'website:deleta_funcionario' funcionario.id %}">Excluir</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>Nenhum funcionário cadastrado</p>
{% endif %}
{% endblock %}

</html>

website/templates/website/index.html
{% extends "website/_layouts/base.html" %}
{% load static %}

{% block title %}
Página Inicial
{% endblock %}

{% block conteudo %}
<div class="container mt-4">
    <div class="row">

        <!-- Card: Cadastrar Funcionário -->
        <div class="col-lg-6 col-md-6 col-sm-12 mb-3">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Cadastrar Funcionário</h5>
                    <p class="card-text">
                        Cadastre aqui um novo <code>Funcionário</code>.
                    </p>
                    <a href="{% url 'website:cadastra_funcionario' %}" class="btn btn-primary">
                        Novo Funcionário
                    </a>
                </div>
            </div>
        </div>

        <!-- Card: Lista de Funcionários -->
        <div class="col-lg-6 col-md-6 col-sm-12 mb-3">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Lista de Funcionários</h5>
                    <p class="card-text">
                        Veja a lista de <code>Funcionários</code> cadastrados.
                    </p>
                    <a href="{% url 'website:lista_funcionarios' %}" class="btn btn-primary">
                        Ver Funcionários
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}


website/templates/website/lista.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Funcionários</title>

    {% load primeira_letra %}
</head>
<body>

<h1>Lista de Funcionários</h1>

<a href="{% url 'website:cadastra_funcionario' %}">
    Cadastrar novo
</a>

<hr>

{% if funcionarios %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th></th>
                <th>Nome</th>
                <th>Sobrenome</th>
                <th>Tempo de Serviço</th>
                <th>Remuneração</th>
                <th class="text-center">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for funcionario in funcionarios %}
            <tr>
                <td>{{ funcionario.nome|primeira_letra }}</td>
                <td>{{ funcionario.nome }}</td>
                <td>{{ funcionario.sobrenome }}</td>
                <td>{{ funcionario.tempo_de_servico }}</td>
                <td>{{ funcionario.remuneracao }}</td>
                <td class="text-center">
                    <a class="btn btn-primary"
                       href="{% url 'website:atualiza_funcionario' funcionario.id %}">
                        Editar
                    </a>
                    <a class="btn btn-danger"
                       href="{% url 'website:deleta_funcionario' funcionario.id %}">
                        Excluir
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Nenhum funcionário cadastrado</p>
{% endif %}

</body>
</html>
